version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: socialapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/user_service:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/socialapp
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres

  post_service:
    build:
      context: ./services/post_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/post_service:/app/services/post_service
      - ./shared:/app/shared
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/socialapp
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres

  comment_service:
    build:
      context: ./services/comment_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/comment_service:/app/services/comment_service
      - ./shared:/app/shared
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/socialapp
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres

  analytics_service:
    build:
      context: ./services/analytics_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/analytics_service:/app
      - ./shared:/app/shared
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/socialapp
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data:
