apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: social-media-app
data:
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: social-media-app
data:
  REACT_APP_API_URL: "http://backend:80"
  NODE_ENV: "production" 