# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   namespace: social-media-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: social-media-frontend:latest
#         ports:
#         - containerPort: 80
#         envFrom:
#         - configMapRef:
#             name: frontend-config
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "100m"
#           limits:
#             memory: "256Mi"
#             cpu: "200m" 