global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'analytics_service'
    static_configs:
      - targets: ['analytics_service:8000']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:8000']

  - job_name: 'post_service'
    static_configs:
      - targets: ['post_service:8000']

  - job_name: 'comment_service'
    static_configs:
      - targets: ['comment_service:8000'] 